workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.afonso.qzerocerto
      
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: "6755795751"
      
      node: v20.10.0
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Install npm dependencies
        script: npm install
      
      - name: Build web assets
        script: npm run build
      
      - name: Sync Capacitor
        script: npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install
      
      - name: Verify GoogleService-Info.plist
        script: |
          if [ -f "$CM_BUILD_DIR/ios/App/App/GoogleService-Info.plist" ]; then
            echo "✅ GoogleService-Info.plist found"
            cat "$CM_BUILD_DIR/ios/App/App/GoogleService-Info.plist" | head -20
          else
            echo "❌ GoogleService-Info.plist NOT FOUND - Firebase will be disabled"
          fi
      
      - name: Set up code signing
        script: xcode-project use-profiles
      
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo "0")
          agvtool new-version -all $(($LATEST + 1))
      
      - name: Build IPA
        script: |
          cd $CM_BUILD_DIR/ios/App
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --ipa-directory $CM_BUILD_DIR/build/ios/ipa
    
    artifacts:
      - build/ios/ipa/*.ipa
      - ios/App/build/ios/ipa/*.ipa
      - $CM_BUILD_DIR/build/ios/ipa/*.ipa
      - "**/*.ipa"
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - afonso@qzero.app
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
